server:
  port: 8191
  servlet:
    context-path: /
spring:
  datasource:
    driver-class: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/insta_bot?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: 1Qwe2Asd3Zxc
    application:
      name: bot-client
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    cache: false
  web:
    resources:
      static-locations: file:src/main/resources/static/
